---
title: "Per protocol"
author: "Pernille Breili"
date: "2023-03-03"
output: html_document
---

```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# VISCERALT FETT
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post i prosent og endringsscore for bruk i statistiske tester
pp.vat.stat <- Resultatskjema %>%
  select(id, sex, group, time, vat_mass) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                        labels = c("Intervensjon", "Kontroll"))) %>% 
  pivot_wider(names_from = time,
              values_from = vat_mass) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.vat.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# analyse av endringsscore fra pre til post mellom gruppene
pp.vat.lm <- lm(change ~ group, data = pp.vat.stat)
summary(pp.vat.lm)

pp.vat.lm.co <- lm(change ~ group + sex, data = pp.vat.stat)
summary(pp.vat.lm.co)

pp.vat.lm.co2 <- lm(change ~ group + sex + Pre, data = pp.vat.stat)
summary(pp.vat.lm.co2)

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.vat <- pp.vat.stat %>%
  summarise(mean.vat.change = mean(change),
            sd.vat.change = sd(change)) %>%
  print()

# lager graf for gjennomsnittsscore i prosent med individuelle endringer (JOBB MER MED DENNE)
mean.pp.vat %>%
  ggplot(aes(group, mean.vat.change, group = group)) + geom_boxplot(width = 0.3, aes(group = group)) + geom_point(data = pp.vat.stat, aes(group, change, group = id), size = 2, alpha = 0.5) + geom_errorbar(aes(ymin = mean.vat.change - sd.vat.change, ymax = mean.vat.change + sd.vat.change), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Endring i visceralt fett (g)") + theme(axis.title = element_text(size = 11), axis.text.x = element_text(size = 11), axis.text.y = element_text(size = 11)) #theme(aspect.ratio = 2/1)


mean.pp.vat %>%
  ggplot(aes(group, mean.vat.change, group = group)) + geom_boxplot(width = 0.1, aes(group = group)) + geom_errorbar(aes(ymin = mean.vat.change - sd.vat.change, ymax = mean.vat.change + sd.vat.change), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Endring i visceralt fett (g)") + theme(axis.title = element_text(size = 11))


pp.vat.stat2 <- Resultatskjema %>%
  select(id, sex, group, time, vat_mass) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"))) %>%
  group_by(group, time) %>%
  drop_na() %>%
  summarise(m = mean(vat_mass),
            s = sd(vat_mass)) %>%
  print()

pp.vat.stat.ind <- Resultatskjema %>%
  select(id, sex, group, time, vat_mass) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"))) %>%
  group_by(group, time) %>%
  drop_na() %>%
  print()

pp.vat.stat2 %>%
  ggplot(aes(x = interaction(time, group), y = m, group = group)) + geom_col(width = 0.5, fill = "white", colour = "black") + geom_line(data = pp.vat.stat.ind, aes(x = interaction(time, group), y = vat_mass, group = id), alpha = 0.4) + geom_point(data = pp.vat.stat.ind, aes(x = interaction(time, group), y = vat_mass, group = id), alpha = 0.4) + theme_classic() + scale_y_continuous(expand = c(0,0)) + geom_errorbar(aes(ymin = m - s, ymax = m + s), width = 0.1)


pp.vat.stat2 %>%
  ggplot(aes(x = interaction(time, group), y = m, group = group)) + geom_col(width = 0.5, fill = "white", colour = "black") + theme_classic() + scale_y_continuous(expand = c(0,0)) + geom_errorbar(aes(ymin = m - s, ymax = m + s), width = 0.1)
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# MIDJEOMKRETS
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post i prosent og endringsscore for bruk i statistiske tester
pp.wc.stat <- Resultatskjema %>%
  select(id, sex, group, time, wc) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(wc = as.numeric(wc, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                        labels = c("Intervensjon", "Kontroll"))) %>% 
  pivot_wider(names_from = time,
              values_from = wc) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.wc.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# analyse av endringsscore fra pre til post mellom gruppene
pp.wc.lm <- lm(change ~ group, data = pp.wc.stat)
summary(pp.wc.lm)

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.wc <- pp.wc.stat %>%
  summarise(mean.wc.pros = mean(change.pros),
            sd.wc.pros = sd(change.pros)) %>%
  print()

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.wc %>%
  ggplot(aes(group, mean.wc.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.wc.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.wc.pros - sd.wc.pros, ymax = mean.wc.pros + sd.wc.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Midjeomkrets (% endring)")

```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# BLODLIPIDER
#Triglyserider
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post
pp.trigl.stat <- Resultatskjema %>%
  select(id, sex, group, time, `s-triglyserider`) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(`s-triglyserider` = as.numeric(`s-triglyserider`, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                       labels = c("Intervensjon", "Kontroll"))) %>%
  pivot_wider(names_from = time,
              values_from = `s-triglyserider`) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.trigl.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.trigl <- pp.trigl.stat %>%
  summarise(mean.trigl.pros = mean(change.pros),
            sd.trigl.pros = sd(change.pros)) %>%
  print()

# analyse av endringsscore fra pre til post mellom gruppene
pp.trigl.lm <- lm(change ~ group, data = pp.trigl.stat)
summary(pp.trigl.lm)

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.trigl %>%
  ggplot(aes(group, mean.trigl.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.trigl.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.trigl.pros - sd.trigl.pros, ymax = mean.trigl.pros + sd.trigl.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Triglyserider (% endring)")
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# BLODLIPIDER
# LDL
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post
pp.ldl.stat <- Resultatskjema %>%
  select(id, sex, group, time, `s-ldl`) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(`s-ldl` = as.numeric(`s-ldl`, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                       labels = c("Intervensjon", "Kontroll"))) %>%
  pivot_wider(names_from = time,
              values_from = `s-ldl`) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.ldl.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.ldl <- pp.ldl.stat %>%
  summarise(mean.ldl.pros = mean(change.pros),
            sd.ldl.pros = sd(change.pros)) %>%
  print()

# analyse av endringsscore fra pre til post mellom gruppene
pp.ldl.lm <- lm(change ~ group, data = pp.ldl.stat)
summary(pp.ldl.lm)

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.ldl %>%
  ggplot(aes(group, mean.ldl.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.ldl.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.ldl.pros - sd.ldl.pros, ymax = mean.ldl.pros + sd.ldl.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "LDL-kolesterol (% endring)")
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# BLODLIPIDER
# HDL
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post
pp.hdl.stat <- Resultatskjema %>%
  select(id, sex, group, time, `s-hdl`) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(`s-hdl` = as.numeric(`s-hdl`, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                       labels = c("Intervensjon", "Kontroll"))) %>%
  pivot_wider(names_from = time,
              values_from = `s-hdl`) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.hdl.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.hdl <- pp.hdl.stat %>%
  summarise(mean.hdl.pros = mean(change.pros),
            sd.hdl.pros = sd(change.pros)) %>%
  print()

# analyse av endringsscore fra pre til post mellom gruppene
pp.hdl.lm <- lm(change ~ group, data = pp.hdl.stat)
summary(pp.hdl.lm)

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.hdl %>%
  ggplot(aes(group, mean.hdl.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.hdl.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.hdl.pros - sd.hdl.pros, ymax = mean.hdl.pros + sd.hdl.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "HDL-kolesterol (% endring)")
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# GLUKOSE
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post
pp.gluk.stat <- Resultatskjema %>%
  select(id, sex, group, time, `s-glukose`) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(`s-glukose` = as.numeric(`s-glukose`, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                       labels = c("Intervensjon", "Kontroll"))) %>%
  pivot_wider(names_from = time,
              values_from = `s-glukose`) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.gluk.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.gluk <- pp.gluk.stat %>%
  summarise(mean.gluk.pros = mean(change.pros),
            sd.gluk.pros = sd(change.pros)) %>%
  print()

# analyse av endringsscore fra pre til post mellom gruppene
pp.gluk.lm <- lm(change ~ group, data = pp.gluk.stat)
summary(pp.gluk.lm)

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.gluk %>%
  ggplot(aes(group, mean.gluk.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.gluk.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.gluk.pros - sd.gluk.pros, ymax = mean.gluk.pros + sd.gluk.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Glukose (% endring)")
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(pbkrtest); library(broom)
Resultatskjema <- read_excel("Resultatskjema.xlsx")
# ARTERIELL STIVHET
# ordner et datasett for grafisk fremstilling med individuelle endringer fra pre til post
pp.pwv.stat <- Resultatskjema %>%
  select(id, sex, group, time, pwv) %>%
  filter(id != "tr031 012") %>% 
  filter(id != "tr031 013") %>% 
  filter(id != "tr031 010") %>% 
  filter(id != "tr031 007") %>% 
  mutate(pwv = as.numeric(pwv, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post"),
                       labels = c("Pre", "Post")),
         group = factor(group, levels = c("fls", "kon"),
                       labels = c("Intervensjon", "Kontroll"))) %>%
  pivot_wider(names_from = time,
              values_from = pwv) %>%
  mutate(change = Post - Pre) %>%
  mutate(change.pros = ((Post - Pre)/ Pre) * 100) %>%
  group_by(group) %>%
  drop_na() %>%
  print()

# sjekker normalfordelingen 
ggplot(pp.pwv.stat, aes(sample = change)) + stat_qq() + stat_qq_line(col = "red")

# lager et datasett med gjennomsnittsverdier av prosentvis endring for bruk i graf
mean.pp.pwv <- pp.pwv.stat %>%
  summarise(mean.pwv.pros = mean(change.pros),
            sd.pwv.pros = sd(change.pros)) %>%
  print()

# analyse av endringsscore fra pre til post mellom gruppene
pp.pwv.lm <- lm(change ~ group, data = pp.pwv.stat)
summary(pp.pwv.lm)

# lager graf for gjennomsnittsscore i prosent med individuelle endringer
mean.pp.pwv %>%
  ggplot(aes(group, mean.pwv.pros, group = group)) + geom_point(size = 3, aes(group = group)) + geom_point(data = pp.pwv.stat, aes(group, change.pros, group = id), position = position_dodge(width = 0.2), size = 2, alpha = 0.4) + geom_errorbar(aes(ymin = mean.pwv.pros - sd.pwv.pros, ymax = mean.pwv.pros + sd.pwv.pros), position = position_dodge(width = 0.2), width = 0.05) + theme_classic() + labs(x = "Gruppe", y = "Pulsbølgehastighet (% endring)")
```


