---
title: "ITT"
author: "Pernille Breili"
date: "2023-02-28"
output: html_document
---

```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable)
Resultatskjema <- read_excel("Resultatskjema.xlsx")

# lage en tabell for alle hovedvariabler med endringer fra pr til post og endringsscore
itt <- Resultatskjema %>%
  select(id, group, time, wc, vat_mass, vat_volume, `s-glukose`, `s-triglyserider`, `s-hdl`, `s-ldl`, pwv) %>%
  # endrer fra chr til dbl
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(vat_volume = as.numeric(vat_volume, na.rm = TRUE)) %>%
  mutate(`s-glukose` = as.numeric(`s-glukose`, na.rm = TRUE)) %>%
  mutate(`s-triglyserider` = as.numeric(`s-triglyserider`, na.rm = TRUE)) %>%
  mutate(`s-hdl` = as.numeric(`s-hdl`, na.rm = TRUE)) %>%
  mutate(`s-ldl` = as.numeric(`s-ldl`, na.rm = TRUE)) %>%
  mutate(pwv = as.numeric(pwv, na.rm = TRUE)) %>%
  # skiller pre og post verdier i to kolonner
  pivot_longer(names_to = "variable",
               values_to = "value", 
               cols = wc:pwv) %>%
  pivot_wider(names_from = time,
              values_from = value) %>%
  drop_na() %>%
  mutate(change = post - pre) %>%
  print()

# lage et datasett som teller antall observasjoner av hovedvariablene   
itt.count <- Resultatskjema %>%
  select(id, group, time, wc, vat_mass, vat_volume, `s-glukose`, `s-triglyserider`, `s-hdl`, `s-ldl`, pwv) %>%
  # endrer fra chr til dbl
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(vat_volume = as.numeric(vat_volume, na.rm = TRUE)) %>%
  mutate(`s-glukose` = as.numeric(`s-glukose`, na.rm = TRUE)) %>%
  mutate(`s-triglyserider` = as.numeric(`s-triglyserider`, na.rm = TRUE)) %>%
  mutate(`s-hdl` = as.numeric(`s-hdl`, na.rm = TRUE)) %>%
  mutate(`s-ldl` = as.numeric(`s-ldl`, na.rm = TRUE)) %>%
  mutate(pwv = as.numeric(pwv, na.rm = TRUE)) %>%
  # skiller pre og post verdier i to kolonner
  pivot_longer(names_to = "variable",
               values_to = "value", 
               cols = wc:pwv) %>%
  pivot_wider(names_from = time,
              values_from = value) %>%
  drop_na() %>%
  count(variable, group) %>%
  print()
```
```{r}
library(tidyverse); library(knitr); library(ggplot2); library(kableExtra); library(readxl); library(dplyr); library(flextable); library(lme4); library(emmeans); library(pbkrtest)
Resultatskjema <- read_excel("Resultatskjema.xlsx")

itt.vat <- Resultatskjema %>%
  select(id, group, time, vat_mass) %>%
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  mutate(time = factor(time, levels = c("pre", "post")),
         group = factor(group, levels = c("fls", "kon"))) %>%
  drop_na() %>%
  print()

# undersøker endringer fra pre til post for hver fp 
itt.vat %>%
  ggplot(aes(time, vat_mass, group = id, color = group)) + geom_line() +   geom_boxplot(aes(group = NULL), width = 0.5) + theme_minimal()

# fit mixed models med lme4
vat.m1 <- lmer(vat_mass ~ time * group + (1|id), data = itt.vat)
plot(vat.m1)
est <- emmeans(vat.m1, specs = ~ time|group)

est %>%
  data.frame() %>%
  ggplot(aes(time, emmean, group = group, color = group)) + 
  geom_line(data = itt.vat, aes(time, vat_mass, group = id, color = group), 
            # Add transparency to individual lines
            alpha = 0.4) + 
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), 
                position = position_dodge(width = 0.2), 
                width = 0.1) + geom_line(position = position_dodge(width = 0.2)) + geom_point(position = position_dodge(width = 0.2)) +
  theme_minimal()
# fortsett her 

itt.vat.mean <- Resultatskjema %>%
  select(id, group, time, vat_mass) %>%
  group_by(group) %>%
  mutate(vat_mass = as.numeric(vat_mass, na.rm = TRUE)) %>%
  pivot_wider(names_from = time,
              values_from = vat_mass) %>%
  # dropper alle na-verdier, tar bort fp som ikke har verdier på pre eller post 
  drop_na() %>%
  mutate(n = n()) %>%
  # lager en endringsscore
  mutate(change = post - pre) %>%
  print()

summary(lm(post ~ pre + group, data = itt.vat))
summary(lm(change ~ pre + group, data = itt.vat))

m.linear <- lm(post ~ pre + group,  data = itt.vat)

ggplot(aes(time, group))

```


